# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0002_auto_20171031_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paperinteraction',
            options={'managed': True},
        ),
    ]
