# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0004_auto_20171031_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='paper_interaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='justifications.PaperInteraction'),
        ),
    ]
