# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0005_evidence_paper_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='interaction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='pmcid',
            field=models.CharField(max_length=255),
        ),
    ]
