# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:31
from __future__ import unicode_literals

from django.db import migrations


def update_paper_interactions(apps, schema_editor):
    Evidence = apps.get_model('justifications', 'Evidence')
    PaperInteraction = apps.get_model('justifications', 'PaperInteraction')

    for e in Evidence.objects.all():
        pi = PaperInteraction.objects.get(pmcid=e.pmcid, interaction=e.interaction)
        e.paper_interaction = pi
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('justifications', '0006_auto_20171031_0625'),
    ]

    operations = [
        migrations.RunPython(update_paper_interactions)
    ]
